kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"      # Listen on all interfaces
  apiServerPort: 6443              # Expose on port 6443

nodes:
  - role: control-plane